# Generated by Django 5.0.7 on 2026-07-27 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('bkash', 'bKash')], max_length=10)),
                ('transaction_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['order'], name='payments_order_i_b32b33_idx'), models.Index(fields=['provider'], name='payments_provide_b98dc8_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx')],
            },
        ),
    ]
